# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    self.driver.get("https://magento.softwaretestingboard.com/gear/bags.html")
    self.driver.find_element(By.CSS_SELECTOR, ".header:nth-child(2) > .customer-welcome .action").click()
    self.driver.find_element(By.LINK_TEXT, "Sign Out").click()
    self.driver.find_element(By.LINK_TEXT, "Create an Account").click()
    self.driver.find_element(By.ID, "firstname").click()
    self.driver.find_element(By.ID, "firstname").send_keys("tarek")
    self.driver.find_element(By.ID, "lastname").click()
    self.driver.find_element(By.ID, "lastname").send_keys("monoar")
    self.driver.find_element(By.CSS_SELECTOR, ".field:nth-child(3) span").click()
    self.driver.find_element(By.ID, "email_address").send_keys("fake@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".field:nth-child(4)").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("tarek1234Tarek")
    self.driver.find_element(By.ID, "password-confirmation").click()
    self.driver.find_element(By.ID, "password-confirmation").send_keys("tarek1234Tarek")
    self.driver.find_element(By.CSS_SELECTOR, ".submit > span").click()
    self.driver.execute_script("window.scrollTo(0,238)")
    self.driver.find_element(By.ID, "option-label-size-143-item-167").click()
    self.driver.find_element(By.ID, "option-label-color-93-item-50").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".product-addto-links > .towishlist > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#product-addtocart-button > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#product-addtocart-button > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "shopping cart").click()
    self.driver.find_element(By.CSS_SELECTOR, ".checkout > span").click()
    self.driver.find_element(By.ID, "NHV6K9G").click()
    self.driver.find_element(By.ID, "NHV6K9G").send_keys("abc pvt ltd")
    self.driver.find_element(By.ID, "J07QBRA").click()
    self.driver.find_element(By.ID, "J07QBRA").send_keys("123/4")
    self.driver.find_element(By.ID, "JIAEGNK").click()
    self.driver.find_element(By.ID, "JIAEGNK").send_keys("dhaka")
    self.driver.find_element(By.CSS_SELECTOR, ".field:nth-child(6)").click()
    self.driver.find_element(By.ID, "ICOJW1Q").click()
    dropdown = self.driver.find_element(By.ID, "ICOJW1Q")
    dropdown.find_element(By.XPATH, "//option[. = 'California']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#ICOJW1Q > option:nth-child(13)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".field:nth-child(8)").click()
    self.driver.find_element(By.ID, "B1TNG4N").click()
    self.driver.find_element(By.ID, "B1TNG4N").send_keys("1204")
    self.driver.find_element(By.ID, "PGHNQDT").click()
    dropdown = self.driver.find_element(By.ID, "PGHNQDT")
    dropdown.find_element(By.XPATH, "//option[. = 'Uganda']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(232)").click()
    self.driver.find_element(By.ID, "B1TNG4N").click()
    self.driver.find_element(By.ID, "B1TNG4N").send_keys("12042344")
    self.driver.find_element(By.ID, "shipping-new-address-form").click()
    self.driver.find_element(By.ID, "PGHNQDT").click()
    dropdown = self.driver.find_element(By.ID, "PGHNQDT")
    dropdown.find_element(By.XPATH, "//option[. = 'Turkmenistan']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(229)").click()
    self.driver.find_element(By.ID, "B1TNG4N").click()
    self.driver.find_element(By.ID, "B1TNG4N").send_keys("123456")
    self.driver.find_element(By.ID, "ARA556M").click()
    self.driver.find_element(By.ID, "ARA556M").send_keys("0123456789")
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".checkout > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".continue > span").click()
  
